# This file is a template, and might need editing before it works on your project.
image: elixir:latest

stages: ["deps", "test"]

.test: &test
  stage: test
  variables:
    MIX_ENV: test
  dependencies:
    - deps
  before_script:
    - mix local.rebar --force
    - mix local.hex --force

deps:
  stage: deps
  artifacts:
    paths:
      - deps
      - _build
  cache:
    key: "${CI_JOB_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - deps
      - _build
    policy: pull-push
  script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
    - MIX_ENV=test mix compile

test:formatter:
  <<: *test
  script:
    - mix format --check-formatted

test:credo:
  <<: *test
  script:
    - mix credo

test:unit:
  <<: *test
  script:
    - mix test
